### ISSUE TITLE
Compress with LZ-String Javascript edition and Decompress with C# Edition

### ISSUE THREAD

**Issue by supakit1** [jawa-the-hutt/lz-string-csharp#17]
Hi,

I tried to compress with C# and sending this file to mobile and decompress with javascript edition. Error occured. Your c# version support decompress from JS ?  LZ-String JS Version is 1.3.4 for C# I using latest version.

BR,

**Comment by christianrondeau** [comment]
Hey @supakit1 ! We already have tests to validate that js-to-c# and c#-to-js work: https://github.com/jawa-the-hutt/lz-string-csharp/blob/master/tests/LZStringTests.cs#L150 (you'll see it actually runs node to make sure). Keep in mind that most of the deserialization errors might come from transfer loss (e.g. if you use decompress, it uses the whole UTF-16 byte size, which gets damaged when transferring over HTTP).

If you believe it's a bug, can you provide a replication test? Otherwise, make sure you use something that supports being sent over HTTP, like  `CompressEncodedURIComponent`

**Comment by supakit1** [comment]
Hi,

I checked as your suggestion. Now it work perfectly.

Thanks ,


On 29 Nov 2017, at 04:09, Christian Rondeau <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey @supakit1<https://github.com/supakit1> ! We already have tests to validate that js-to-c# and c#-to-js work: https://github.com/jawa-the-hutt/lz-string-csharp/blob/master/tests/LZStringTests.cs#L150 (you'll see it actually runs node to make sure). Keep in mind that most of the deserialization errors might come from transfer loss (e.g. if you use decompress, it uses the whole UTF-16 byte size, which gets damaged when transferring over HTTP).

If you believe it's a bug, can you provide a replication test? Otherwise, make sure you use something that supports being sent over HTTP, like CompressEncodedURIComponent
